name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push python-docker as branch
        uses: alexmaccalman/github-pages-deploy-action@releases/v3 # This is an example action that can push a subdirectory as a branch
        with:
          BRANCH: python-docker-branch # The branch where you want to push your subdirectory
          FOLDER: python-docker # The folder you want to deploy

      - name: Checkout python-docker-branch
        uses: actions/checkout@v3 
        with:
          ref: python-docker-branch # The branch where your subdirectory is pushed

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile # You don't need to specify the subdirectory here because it is already checked out as the root directory of this branch 
          push: true 
          tags : ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest 
       
